# Generated by Django 5.2.1 on 2025-05-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBNNo', models.IntegerField()),
                ('Title', models.CharField()),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('UserName', models.CharField()),
                ('UserPassword', models.CharField()),
                ('UserTypeSeller', models.BooleanField()),
            ],
        ),
    ]
